Repository friction2d/friction, pull requests merged in 2024-11, with the labels that each got.

#312 UI/UX: New ToolBar
  src/app/GUI/Settings/generalsettingswidget.cpp
  src/app/GUI/Settings/generalsettingswidget.h
  src/app/GUI/mainwindow.cpp
  src/app/GUI/mainwindow.h
  src/app/GUI/toolbox.cpp
  src/app/friction.qss
  src/core/Private/esettings.cpp
  src/core/Private/esettings.h
  src/ui/CMakeLists.txt
  src/ui/widgets/colortoolbar.cpp
  src/ui/widgets/toolbar.cpp
  src/ui/widgets/toolbar.h
  src/ui/widgets/vlabel.h
  src/ui/widgets/welcomedialog.cpp
Labels: enhancement, ui, ux

#316 Duration value converts from frames to seconds and viceversa
  src/ui/dialogs/scenesettingsdialog.cpp
  src/ui/dialogs/scenesettingsdialog.h
Labels: ux

#323 Timeline: interactive markers/in/out
  src/core/canvas.cpp
  src/core/canvas.h
  src/ui/widgets/framescrollbar.cpp
  src/ui/widgets/framescrollbar.h
Labels: ux

#344 Svg import: fix colors
  src/core/svgimporter.cpp
Labels: bug, svg import, color

#349 SVG Export: support follow path (effect)
  src/core/Animators/graphanimator.cpp
  src/core/Animators/graphanimator.h
  src/core/Animators/qpointfanimator.cpp
  src/core/Animators/qpointfanimator.h
  src/core/Animators/qrealanimator.cpp
  src/core/Animators/qrealanimator.h
  src/core/Boxes/boundingbox.cpp
  src/core/Boxes/boundingbox.h
  src/core/Boxes/containerbox.cpp
  src/core/TransformEffects/followpatheffect.cpp
  src/core/TransformEffects/followpatheffect.h
  src/core/TransformEffects/transformeffectcollection.cpp
  src/core/TransformEffects/transformeffectcollection.h
  src/core/appsupport.cpp
  src/core/appsupport.h
  src/core/canvasselectedboxesactions.cpp
Labels: enhancement, svg export, svg

#339 New null object type
  src/core/Boxes/nullobject.cpp
Labels: enhancement
