Repository friction2d/friction, pull requests merged in 2025-04, with the labels that each got.

#494 UX: Draw/Stroke/Fill better workflow
  src/app/GUI/mainwindow.cpp
  src/app/GUI/mainwindow.h
  src/core/Animators/outlinesettingsanimator.h
  src/core/Animators/paintsettingsanimator.cpp
  src/core/Animators/paintsettingsanimator.h
  src/core/Boxes/pathbox.cpp
  src/core/Boxes/textbox.cpp
  src/core/Private/esettings.h
  src/core/appsupport.cpp
  src/core/appsupport.h
  src/core/canvas.cpp
  src/core/canvasmouseevents.cpp
  src/ui/dialogs/scenesettingsdialog.cpp
  src/ui/widgets/fillstrokesettings.cpp
Labels: ux, draw, rectangle, circle, fill/stroke, text

#473 SVG Export: added DstOut blend mode
  src/core/Boxes/boundingbox.cpp
  src/core/Boxes/containerbox.cpp
Labels: svg export

#478 Rewind / Fast Forward by quarters
  src/app/GUI/timelinedockwidget.cpp
  src/app/GUI/timelinedockwidget.h
Labels: ux
