Repository friction2d/friction, pull requests merged in 2025-02, with the labels that each got.

#442 Undo: support scene changes
  src/core/canvas.cpp
  src/core/canvas.h
Labels: undo

#443 Playback based on preview steps
  src/app/GUI/mainwindow.cpp
  src/app/GUI/timelinedockwidget.cpp
  src/app/GUI/timelinedockwidget.h
  src/core/Private/esettings.cpp
  src/core/Private/esettings.h
Labels: enhancement, ui, ux, timeline

#445 Value slider: fixes + uniform support
  src/ui/widgets/qrealanimatorvalueslider.cpp
  src/ui/widgets/qrealanimatorvalueslider.h
Labels: enhancement, ux
